name: lboard

description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_object_detection: ^0.15.0
  sqflite: ^2.3.2
  sembast: ^3.4.2
  sembast_web: ^2.4.2
  sqflite_common_ffi: ^2.3.2
  sqflite_common: ^2.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^10.0.0-beta.4
  dio: ^5.1.0
  path: ^1.9.1
  provider: ^6.1.3
  logging: ^1.0.2
  logger: ^2.5.0
  mqtt_client: ^10.9.2

  flutter_mqtt: ^1.0.0+5

  flutter_localizations:
    sdk: flutter

  # For date/time picker and formatting
  intl: ^0.20.2

  # For loading indicators, shimmer effects, etc.
  flutter_spinkit: ^5.2.0
  flutter_map_marker_popup: ^8.0.1

  # For improved forms (optional)
  flutter_form_builder: ^10.0.1
  go_router: ^15.1.2
  # For image loading and caching
  cached_network_image: ^3.2.3

  image_picker: ^1.1.2

  # HTTP client for API calls
  http: ^1.4.0
  # State management
  flutter_bloc: ^9.1.1

  # For caching FMCSA data
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For capturing screenshots
  screenshot: ^3.0.0

  # For file operations
  file_picker: ^10.2.0
  map: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sqflite_migration: ^0.3.0
  google_maps_flutter: ^2.11.1
  flutter_map: ^8.1.1
  flutter_polyline_points: ^2.1.0
  geolocator: ^14.0.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  google_maps_flutter_platform_interface: ^2.12.1
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi_web: ^1.0.0
  flutter_launcher_icons: ^0.14.4
  # For testing
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.21.0
flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
image_path: "assets/icons/icon.png"
pubspec:
    android: true
    ios: true
    windows: true
    macos: true
plugins:
    android: true
    ios: true
    windows: true
    macos: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/icons/icon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #